#!/bin/bash

which docker-machine
if [[ $? -ne 0 ]]; then
  sudo installer -pkg /Volumes/nanobox/.DockerToolbox.pkg -target /
fi

which nanobox
if [[ $? -ne 0 ]]; then
  sudo ln -sf /opt/nanobox/bin/nanobox /usr/local/bin/nanobox
fi

# In some cases the opt folder doesn't exists before Vagrant/nanobox
# install. This folder must be always hidden.
chflags hidden /opt

# Exit with a success code
exit 0
