#!/bin/bash

which vboxmanage
if [[ $? -ne 0 ]]; then
  hdiutil mount /Volumes/nanobox/.virtualbox.dmg 
  sudo installer -pkg /Volumes/VirtualBox/VirtualBox.pkg -target /
  hdiutil unmount /Volumes/VirtualBox/
fi

which vagrant
if [[ $? -ne 0 ]]; then
  hdiutil mount /Volumes/nanobox/.vagrant.dmg
  sudo installer -pkg /Volumes/Vagrant/Vagrant.pkg -target /
  hdiutil unmount /Volumes/Vagrant
fi

vagrant box list  | grep '^nanobox/boot2docker ' &> /dev/null
if [[ $? -ne 0 ]]; then
  vagrant box add --name nanobox/boot2docker
fi

which nanobox
if [[ $? -ne 0 ]]; then
  sudo ln -sf /opt/nanobox/bin/nanobox /usr/local/bin/nanobox
fi

# In some cases the opt folder doesn't exists before Vagrant/nanobox
# install. This folder must be always hidden.
chflags hidden /opt

# Exit with a success code
exit 0
