#!/bin/sh -e
if [ "$1" = "configure" ]; then
  # remove lock in order to preserve package individual-ness
  rm /var/lib/dpkg/lock
  dpkg -s virtualbox-5.0 > /dev/null 2>&1 || dpkg -i /opt/nanobox/share/virtualbox.deb
  dpkg -s vagrant        > /dev/null 2>&1 || dpkg -i /opt/nanobox/share/vagrant.deb
  dpkg -s nanobox        > /dev/null 2>&1 || dpkg -i /opt/nanobox/share/nanobox.deb
  # for whatever reason, dpkg leaves nanobox-bundle half configured.
  # everything is installed, but it needs `dpkg -i`d again.
fi
