#!/bin/sh -e
if [ "$1" = "configure" ]; then
  rm /var/lib/dpkg/lock
  which vboxmanage || dpkg -i /opt/nanobox/share/virtualbox.deb
  which vagrant    || dpkg -i /opt/nanobox/share/vagrant.deb
  which nanobox    || dpkg -i /opt/nanobox/share/nanobox.deb
  touch /var/lib/dpkg/lock
fi
