#!/bin/sh -e
install_vagrant(){
  echo "Installing vagrant..."
  wget -O tmp/vagrant.deb https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
  dpkg -i tmp/vagrant.deb
}

install_virtualbox(){
  echo "Installing virtualbox..."
  wget -O tmp/virtualbox.deb http://download.virtualbox.org/virtualbox/5.0.10/virtualbox-5.0_5.0.10-104061~Ubuntu~trusty_amd64.deb
  dpkg -i tmp/virtualbox.deb
}

install_nanobox(){
  echo "Installing nanobox..."
  wget -O tmp/nanobox.deb https://s3.amazonaws.com/tools.nanobox.io/installers/linux/nanobox.deb
  dpkg -i --ignore-depends=virtualbox tmp/nanobox.deb
}

if [ "$1" = "install" -o "$1" = "upgrade" ]; then
  # check for version
  [ -f /etc/lsb-release ] && . /etc/lsb-release
  if [ "$DISTRIB_RELEASE" != "14.04" -a "$DISTRIB_RELEASE" != "14.10" -a "$DISTRIB_RELEASE" != "15.04" ]; then
    echo "Nanobox bundle is currently bundled for 14.04. Please download the
  correct virtualbox from https://www.virtualbox.org/wiki/Linux_Downloads"
    vbox='no'
  fi

  rm -f /var/lib/dpkg/lock
  [ -z "$vbox" ] && ( dpkg -s virtualbox-5.0 > /dev/null 2>&1 || install_virtualbox ) || true
  dpkg -s vagrant > /dev/null 2>&1 || install_vagrant
  dpkg -s nanobox > /dev/null 2>&1 || install_nanobox
fi
