#!/bin/sh -e
if [ "$1" = "remove" ]; then
  rm /var/lib/dpkg/lock
  which nanobox    && dpkg --purge nanobox
  which vagrant    && dpkg --purge vagrant
  which vboxmanage && dpkg --purge virtualbox-5.0
  touch /var/lib/dpkg/lock
fi
