#!/bin/sh -e
if [ "$1" = "upgrade" -o "$1" = "remove" ]; then
  rm -f /usr/local/bin/nanobox
  vagrant box list | grep '^nanobox/boot2docker ' && vagrant box remove nanobox/boot2docker --force > /dev/null 2>&1 || true

  if [ -L /usr/doc/nanobox ]; then
    rm -f /usr/doc/nanobox
  fi
fi
